DELETE FROM jadwal;
DELETE FROM pegawai;
DELETE FROM jabatan;
INSERT INTO jabatan (id,NAME) VALUES ('1','Direktur Jenderal Kefarmasian dan Alat Kesehatan');
INSERT INTO jabatan (id,NAME) VALUES ('2','Sekretaris Direktorat Jenderal Kefaramasian dan Alat Kesehatan');
INSERT INTO jabatan (id,NAME) VALUES ('3','Kepala Bagian Program dan Informasi');
INSERT INTO jabatan (id,NAME) VALUES ('4','Kepala Bagian  Hukum, Organisasi dan Hubungan Masyarakat');
INSERT INTO jabatan (id,NAME) VALUES ('5','Kepala Bagian Keuangan dan Barang Milik Negara');
INSERT INTO jabatan (id,NAME) VALUES ('6','Kepala Bagian Kepegawaian dan Umum');
INSERT INTO jabatan (id,NAME) VALUES ('7','Kepala Sub Bagian Program');
INSERT INTO jabatan (id,NAME) VALUES ('8','Kepala Sub Bagian Anggaran');
INSERT INTO jabatan (id,NAME) VALUES ('9','Kepala Sub Bagian Informasi dan Evaluasi');
INSERT INTO jabatan (id,NAME) VALUES ('10','Kepala Sub Bagian Peraturan Perundang-undangan');
INSERT INTO jabatan (id,NAME) VALUES ('11','Kepala Sub Bagian Organisasi dan Tatalaksana');
INSERT INTO jabatan (id,NAME) VALUES ('12','Kepala Sub Bagian Advokasi Hukum dan Hubungan Masyarakat');
INSERT INTO jabatan (id,NAME) VALUES ('13','Kepala Sub Bagian Perbendaharaan');
INSERT INTO jabatan (id,NAME) VALUES ('14','Kepala Sub Bagian Verifikasi dan Akuntansi');
INSERT INTO jabatan (id,NAME) VALUES ('15','Kepala Sub Bagian Pengelolaan Barang Milik Negara');
INSERT INTO jabatan (id,NAME) VALUES ('16','Kepala Sub Bagian Kepegawaian');
INSERT INTO jabatan (id,NAME) VALUES ('17','Kepala Sub Bagian Layanan Pengadaan');
INSERT INTO jabatan (id,NAME) VALUES ('18','Kepala Sub Bagian Tata Usaha dan Rumah Tangga');
INSERT INTO jabatan (id,NAME) VALUES ('19','Staf');
